//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ci2.PI.Persistencia.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ci2PIBDEntidades : DbContext
    {
        public Ci2PIBDEntidades()
            : base("name=Ci2PIBDEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<TabEstadoTarea> TabEstadoTarea { get; set; }
        public virtual DbSet<TabRol> TabRol { get; set; }
        public virtual DbSet<TabTarea> TabTarea { get; set; }
        public virtual DbSet<TabUsuario> TabUsuario { get; set; }
        public virtual DbSet<TabUsuarioClaim> TabUsuarioClaim { get; set; }
        public virtual DbSet<TabUsuarioLogin> TabUsuarioLogin { get; set; }
    
        public virtual ObjectResult<Nullable<long>> PraTabTareaAgregarOActualizar(Nullable<long> ci2TareaId, Nullable<System.DateTime> ci2FechaCreacion, string ci2Descripcion, Nullable<long> ci2EstadoTareaId, string ci2UsuarioId)
        {
            var ci2TareaIdParameter = ci2TareaId.HasValue ?
                new ObjectParameter("Ci2TareaId", ci2TareaId) :
                new ObjectParameter("Ci2TareaId", typeof(long));
    
            var ci2FechaCreacionParameter = ci2FechaCreacion.HasValue ?
                new ObjectParameter("Ci2FechaCreacion", ci2FechaCreacion) :
                new ObjectParameter("Ci2FechaCreacion", typeof(System.DateTime));
    
            var ci2DescripcionParameter = ci2Descripcion != null ?
                new ObjectParameter("Ci2Descripcion", ci2Descripcion) :
                new ObjectParameter("Ci2Descripcion", typeof(string));
    
            var ci2EstadoTareaIdParameter = ci2EstadoTareaId.HasValue ?
                new ObjectParameter("Ci2EstadoTareaId", ci2EstadoTareaId) :
                new ObjectParameter("Ci2EstadoTareaId", typeof(long));
    
            var ci2UsuarioIdParameter = ci2UsuarioId != null ?
                new ObjectParameter("Ci2UsuarioId", ci2UsuarioId) :
                new ObjectParameter("Ci2UsuarioId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("PraTabTareaAgregarOActualizar", ci2TareaIdParameter, ci2FechaCreacionParameter, ci2DescripcionParameter, ci2EstadoTareaIdParameter, ci2UsuarioIdParameter);
        }
    
        public virtual ObjectResult<PraTabTareaConsultarPorId_Result> PraTabTareaConsultarPorId(Nullable<long> ci2TareaId)
        {
            var ci2TareaIdParameter = ci2TareaId.HasValue ?
                new ObjectParameter("Ci2TareaId", ci2TareaId) :
                new ObjectParameter("Ci2TareaId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PraTabTareaConsultarPorId_Result>("PraTabTareaConsultarPorId", ci2TareaIdParameter);
        }
    
        public virtual int PraTabTareaEliminar(Nullable<long> ci2TareaId)
        {
            var ci2TareaIdParameter = ci2TareaId.HasValue ?
                new ObjectParameter("Ci2TareaId", ci2TareaId) :
                new ObjectParameter("Ci2TareaId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PraTabTareaEliminar", ci2TareaIdParameter);
        }
    
        public virtual ObjectResult<PraTabTareaListar_Result> PraTabTareaListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PraTabTareaListar_Result>("PraTabTareaListar");
        }
    }
}
