//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ci2.PI.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabRol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabRol()
        {
            this.TabUsuario = new HashSet<TabUsuario>();
        }
    
        public string LeyRolId { get; set; }
        public string LeyNombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabUsuario> TabUsuario { get; set; }
    }
}
