//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ci2.PI.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabTarea
    {
        public long Ci2TareaId { get; set; }
        public System.DateTime Ci2FechaCreacion { get; set; }
        public string Ci2Descripcion { get; set; }
        public long Ci2EstadoTareaId { get; set; }
        public string Ci2UsuarioId { get; set; }
    
        public virtual TabEstadoTarea TabEstadoTarea { get; set; }
        public virtual TabUsuario TabUsuario { get; set; }
    }
}
