//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ci2.PI.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabUsuario()
        {
            this.TabTarea = new HashSet<TabTarea>();
            this.TabUsuarioClaim = new HashSet<TabUsuarioClaim>();
            this.TabUsuarioLogin = new HashSet<TabUsuarioLogin>();
            this.TabRol = new HashSet<TabRol>();
        }
    
        public string Ci2UsuarioId { get; set; }
        public string Ci2CorreoElectronico { get; set; }
        public bool Ci2CorreoElectronicoConfirmado { get; set; }
        public string Ci2PasswordHash { get; set; }
        public string Ci2SecurityStamp { get; set; }
        public string Ci2NumeroTelefonico { get; set; }
        public bool Ci2NumeroTelefonicoConfirmado { get; set; }
        public bool Ci2AutenticacionDosEtapasActivado { get; set; }
        public Nullable<System.DateTime> Ci2FechaBloqueoUtc { get; set; }
        public bool Ci2BloqueoActivado { get; set; }
        public int Ci2NumeroAccesosFallidos { get; set; }
        public string Ci2NombreUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabTarea> TabTarea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabUsuarioClaim> TabUsuarioClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabUsuarioLogin> TabUsuarioLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabRol> TabRol { get; set; }
    }
}
