//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ci2.PI.Persistencia.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabUsuarioLogin
    {
        public string Ci2ProvedorLogin { get; set; }
        public string Ci2llaveProvedor { get; set; }
        public string Ci2UsuarioId { get; set; }
    
        public virtual TabUsuario TabUsuario { get; set; }
    }
}
